export const NftLinksForSeeders: string[] = [
    'https://imageio.forbes.com/specials-images/imageserve/6170e01f8d7639b95a7f2eeb/Sotheby-s-NFT-Natively-Digital-1-2-sale-Bored-Ape-Yacht-Club--8817-by-Yuga-Labs/0x0.png?format=png&width=1440',
    'https://cdn.prod.www.spiegel.de/images/d2caafb1-70da-47e2-ba48-efd66565cde1_w996_r0.9975262832405689_fpx44.98_fpy48.86.webp',
    'https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F3eb74dde-cf3a-4f90-8f9a-31ac34b4634c_600x600.jpeg',
    'https://www.artrights.me/wp-content/uploads/2021/09/unnamed-3.png',
    'https://raw.githubusercontent.com/nayanrdeveloper/nuron_nft_marketplace_fronted/master/public/design1.webp',
    'https://raw.githubusercontent.com/nayanrdeveloper/nuron_nft_marketplace_fronted/master/public/design10.jpg',
    'https://raw.githubusercontent.com/nayanrdeveloper/nuron_nft_marketplace_fronted/master/public/design2.webp',
    'https://raw.githubusercontent.com/nayanrdeveloper/nuron_nft_marketplace_fronted/master/public/design3.webp',
    'https://raw.githubusercontent.com/nayanrdeveloper/nuron_nft_marketplace_fronted/master/public/design4.webp',
    'https://raw.githubusercontent.com/nayanrdeveloper/nuron_nft_marketplace_fronted/master/public/design7.jpg',
    'https://raw.githubusercontent.com/nayanrdeveloper/nuron_nft_marketplace_fronted/master/public/design8.webp',
    'https://raw.githubusercontent.com/nayanrdeveloper/nuron_nft_marketplace_fronted/master/public/dsign_9.webp',
    'https://i.imgur.com/Qkw9N0A.jpg',
    'https://i.imgur.com/SMneO6k.jpg',
    'https://i.imgur.com/hMVRFoJ.jpg',
];